using MigDb.Core.Utils.ScriptDom;
using Microsoft.SqlServer.Dac.Compare;
using Microsoft.SqlServer.Dac.Model;
using System.Text;
using System.Text.RegularExpressions;

namespace MigDb.Core.Schema;

public static partial class DacFxUtils
{
    [GeneratedRegex(@"^\s*GO\s*$", RegexOptions.Multiline | RegexOptions.IgnoreCase)]
    private static partial Regex BatchSeparatorRgx();

    [GeneratedRegex(@"/\*.*?\*/", RegexOptions.Singleline)]
    private static partial Regex BlockCommentRgx();

    [GeneratedRegex(@"--[^\n]*")]
    private static partial Regex LineCommentRgx();

    [GeneratedRegex(@"\s+")]
    private static partial Regex WhitespaceRgx();

    [GeneratedRegex(@"\[(?<schema>[^\]]+)\]\.\[(?<name>[^\]]+)\]")]
    private static partial Regex ObjectNameRgx();

    /// <summary>
    /// Attempt to detect what we consider auto generated noise from DacFx
    /// Includes things like TSQL vars, prints, variable sets, etc
    /// </summary>
    /// <param name="sql">SQL string to check</param>
    /// <returns>True if detected, else false</returns>
    private static bool IsNoise(string sql)
    {
        ArgumentNullException.ThrowIfNull(sql);

        string content = BlockCommentRgx().Replace(sql, string.Empty);
        content = LineCommentRgx().Replace(content, string.Empty);
        content = content.Trim();

        if (content.Length == 0)
            return true;

        if (content.StartsWith(':'))
            return true;

        if (content.Contains("$("))
            return true;

        if (content.StartsWith("USE ", StringComparison.OrdinalIgnoreCase))
            return true;

        if (content.StartsWith("PRINT ", StringComparison.OrdinalIgnoreCase))
            return true;

        if (content.StartsWith("SET ", StringComparison.OrdinalIgnoreCase)
            && (content.Contains("ANSI_NULLS", StringComparison.OrdinalIgnoreCase)
                || content.Contains("NUMERIC_ROUNDABORT", StringComparison.OrdinalIgnoreCase)))
            return true;

        return false;
    }

    /// <summary>
    /// Attempts to divide script into batches by execution separator
    /// and return joined denoised script
    /// </summary>
    /// <param name="sql">SQL string</param>
    /// <returns>A denoised script</returns>
    public static string DenoiseScript(string sql)
    {
        ArgumentNullException.ThrowIfNull(sql);

        // need to trim empty spaces in between batches
        IEnumerable<string> scripts = BatchSeparatorRgx()
            .Split(sql)
            .Where(batch => !IsNoise(batch))
            .Select(batch => batch.Trim());

        string result = string.Join("\nGO\n", scripts);

        if (result != string.Empty)
            result += "\nGO\n";

        return result;
    }

    /// <summary>
    /// Checks for auto generated comments from DacFx
    /// might have to update later to keep in sync
    /// </summary>
    /// <param name="comment">comment string</param>
    /// <returns>True if is comment, else falase</returns>
    private static bool IsGeneratedComment(string comment)
    {
        return comment.Contains("generated by a tool", StringComparison.OrdinalIgnoreCase)
           || comment.Contains("Detect SQLCMD mode", StringComparison.OrdinalIgnoreCase);
    }

    /// <summary>
    /// Extract block comment message without the decorators
    /// </summary>
    /// <param name="comment">comment block</param>
    /// <returns>Comment message</returns>
    private static string ExtractBlockCommentText(string comment)
    {
        string inner = comment.Trim();

        if (inner.StartsWith("/*"))
            inner = inner[2..];

        if (inner.EndsWith("*/"))
            inner = inner[..^2];

        return WhitespaceRgx().Replace(inner, " ").Trim();
    }

    /// <summary>
    /// Try extract warnings out of comment block
    /// checks against auto generated comments and returns the rest
    /// </summary>
    /// <param name="sql">SQL Script</param>
    /// <returns>Warning list</returns>
    public static IReadOnlyList<string> ExtractWarnings(string sql)
    {
        ArgumentNullException.ThrowIfNull(sql);

        IEnumerable<string> warnings = BlockCommentRgx()
            .Matches(sql)
            .Select(m => m.Value)
            .Where(comment => !IsGeneratedComment(comment))
            .Select(ExtractBlockCommentText)
            .Where(text => text.Length > 0);

        return [.. warnings];
    }

    /// <summary>
    /// Merges script batches and warnings into a single script
    /// </summary>
    /// <param name="script">The batch script (empty for a warning only object)</param>
    /// <param name="warnings">Plain text warnings to float above it</param>
    /// <returns>The batch with its warnings prepended</returns>
    private static string WithWarnings(string script, IReadOnlyList<string> warnings)
    {
        if (warnings.Count == 0)
            return script;

        StringBuilder sb = new();

        foreach (string warning in warnings)
            sb.Append("/*\n").Append(warning).Append("\n*/\n\n");

        sb.Append(script);

        return sb.ToString();
    }

    public static IReadOnlyList<SchemaObjectScript> SplitScriptsByObject(string sql)
    {
        ArgumentNullException.ThrowIfNull(sql);

        // objects we touch, keyed by "schema.name"
        Dictionary<string, SchemaObject> objects = [];

        // warnings per object
        Dictionary<string, List<string>> objectWarnings = [];

        // every batch in emission order, tagged with the object it targets
        List<ObjectBatch> batches = [];

        foreach (string rawBatch in BatchSeparatorRgx().Split(sql))
        {
            string batch = rawBatch.Trim();

            if (batch.Length == 0)
                continue;

            // strip comments to classify the actual statement
            string statement = BlockCommentRgx().Replace(batch, string.Empty).Trim();

            // a comment-only batch is DacFx warning text, not an object definition
            if (statement.Length == 0)
            {
                foreach (string warning in ExtractWarnings(batch))
                    AttributeWarning(warning, objects, objectWarnings);

                continue;
            }

            SchemaObject? target = ScriptDomUtils.GetSchemaObject(statement);

            if (target is null)
                throw new InvalidOperationException($"Could not determine a target object for batch:\n{batch}");

            string key = $"{target.Schema}.{target.Name}";

            // a real batch classification is authoritative for the kind
            objects[key] = target;

            if (IsProgrammable(target.Kind))
            {
                // a programmable's body is its definition - keep it verbatim (comments and all)
                // and never mistake in-body comments for DacFx warnings
                batches.Add(new ObjectBatch(key, batch));
            }
            else
            {
                // table (or a guard referencing one): comments here are DacFx warnings
                batches.Add(new ObjectBatch(key, statement));

                foreach (string warning in ExtractWarnings(batch))
                    AttributeWarning(warning, objects, objectWarnings, fallbackKey: key);
            }
        }

        List<SchemaObjectScript> result = new(batches.Count);

        HashSet<string> seen = [];

        foreach (ObjectBatch batch in batches)
        {
            List<string> warnings = seen.Add(batch.Key) ? objectWarnings.GetValueOrDefault(batch.Key, []) : [];

            result.Add(new SchemaObjectScript(objects[batch.Key], WithWarnings(batch.Script, warnings), warnings));
        }

        foreach ((string key, SchemaObject obj) in objects)
        {
            if (seen.Contains(key))
                continue;

            List<string> warnings = objectWarnings.GetValueOrDefault(key, []);

            result.Add(new SchemaObjectScript(obj, WithWarnings(string.Empty, warnings), warnings));
        }

        return result;
    }

    private static bool IsProgrammable(SchemaObjectKind kind)
    {
       return kind is SchemaObjectKind.StoredProcedure
             or SchemaObjectKind.View
             or SchemaObjectKind.Function
             or SchemaObjectKind.Trigger;
    }

    private static void AttributeWarning(string warning, Dictionary<string, SchemaObject> objects, Dictionary<string, List<string>> objectWarnings, string? fallbackKey = null)
    {
        MatchCollection matches = ObjectNameRgx().Matches(warning);

        string key;

        if (matches.Count > 0)
        {
            Match match = matches[^1];
            string schema = match.Groups["schema"].Value;
            string name = match.Groups["name"].Value;
            key = $"{schema}.{name}";

            // orphan until (or unless) a batch classifies it - default to a table
            objects.TryAdd(key, new SchemaObject(schema, name, SchemaObjectKind.Table));
        }
        else if (fallbackKey is not null)
        {
            key = fallbackKey;
        }
        else
        {
            return;
        }

        if (!objectWarnings.TryGetValue(key, out List<string>? value))
            objectWarnings.Add(key, [warning]);
        else
            value.Add(warning);
    }

    public static IReadOnlyList<string> SplitScriptByBatch(string sql)
    {
        ArgumentNullException.ThrowIfNull(sql);

        return [.. BatchSeparatorRgx()
            .Split(sql)
            .Select(batch => batch.Trim())
            .Where(batch => batch.Length != 0)];
    }

    public static SchemaDriftItem? ToDriftItem(SchemaDifference difference)
    {
        SchemaDriftKind kind = difference.UpdateAction switch
        {
            SchemaUpdateAction.Add => SchemaDriftKind.MissingFromDatabase,
            SchemaUpdateAction.Delete => SchemaDriftKind.MissingFromProject,
            SchemaUpdateAction.Change => SchemaDriftKind.Different,
            _ => SchemaDriftKind.Different,
        };

        TSqlObject? subject = difference.SourceObject ?? difference.TargetObject;

        if (subject is null)
            return null;

        string name = string.Join('.', subject.Name.Parts);

        IReadOnlyList<string> details = kind == SchemaDriftKind.Different ? [.. Describe(difference)] : [];

        return new SchemaDriftItem(kind, subject.ObjectType.Name, name, details);
    }

    private static IEnumerable<string> Describe(SchemaDifference difference)
    {
        foreach (SchemaDifference child in difference.Children)
        {
            TSqlObject? subject = child.SourceObject ?? child.TargetObject;
            string name = subject is null ? string.Empty : $" {string.Join('.', subject.Name.Parts)}";

            switch (child.UpdateAction)
            {
                case SchemaUpdateAction.Delete:
                    yield return $"{child.Name}{name} in the database only";
                    break;

                case SchemaUpdateAction.Add:
                    yield return $"{child.Name}{name} in the schema project only";
                    break;

                default:
                    foreach (string detail in Describe(child))
                        yield return $"{child.Name}{name}: {detail}";

                    break;
            }
        }
    }
}
