using MigDb.Core.Schema;
using MigDb.Core.Utils.ScriptDom;

namespace MigDb.Test.Core;

public class DacFxUtilsTest
{
    // This is the gross first generated output from dacfx
    // using as a sample to reduce down
    private const string TestSample = """
        /*
        Deployment script for MigDb
        This code was generated by a tool.
        */

        GO
        SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;
        SET NUMERIC_ROUNDABORT OFF;


        GO
        :setvar DatabaseName "MigDb"

        GO
        :on error exit
        GO
        :setvar __IsSqlCmdEnabled "True"
        GO
        IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
            BEGIN
                PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
                SET NOEXEC ON;
            END


        GO
        USE [$(DatabaseName)];


        GO
        /*
        The column [dbo].[Member].[TestC] on table [dbo].[Member] must be added, but the column has no default value and does not allow NULL values. If the table contains data, the ALTER script will not work.
        */

        IF EXISTS (select top 1 1 from [dbo].[Member])
            RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

        GO
        PRINT N'Altering Table [dbo].[Campus]...';


        GO
        ALTER TABLE [dbo].[Campus]
            ADD [TestA] BIT NULL,
                [TestB] BIT NULL;


        GO
        PRINT N'Altering Table [dbo].[Member]...';


        GO
        ALTER TABLE [dbo].[Member]
            ADD [TestC] BIT NOT NULL;


        GO
        """;

    [Fact]
    public void StripSqlCmdPreamble_RemovesSqlCmdDirectivesUseSetOptionsAndPrints()
    {
        string result = DacFxUtils.DenoiseScript(TestSample);

        Assert.DoesNotContain(":setvar", result);
        Assert.DoesNotContain(":on error exit", result);
        Assert.DoesNotContain("$(", result);
        Assert.DoesNotContain("__IsSqlCmdEnabled", result);
        Assert.DoesNotContain("USE [", result);
        Assert.DoesNotContain("NUMERIC_ROUNDABORT", result);
        Assert.DoesNotContain("PRINT", result);
    }

    [Fact]
    public void StripSqlCmdPreamble_KeepsRealDdlAndDataLossGuard()
    {
        string result = DacFxUtils.DenoiseScript(TestSample);

        Assert.Contains("ALTER TABLE [dbo].[Campus]", result);
        Assert.Contains("[TestA] BIT NULL", result);
        Assert.Contains("ALTER TABLE [dbo].[Member]", result);
        Assert.Contains("[TestC] BIT NOT NULL", result);
        Assert.Contains("RAISERROR", result);
    }

    [Fact]
    public void StripSqlCmdPreamble_SeparatesKeptBatchesWithGo()
    {
        string result = DacFxUtils.DenoiseScript(TestSample);

        Assert.Equal(2, result.Split("\nGO\n").Count(b => b.Contains("ALTER TABLE")));
        Assert.EndsWith("GO\n", result);
    }

    [Fact]
    public void StripSqlCmdPreamble_EmptyInput_ReturnsEmpty()
    {
        Assert.Equal(string.Empty, DacFxUtils.DenoiseScript("   \n  GO \n "));
    }

    [Fact]
    public void ExtractWarnings_ReturnsDacFxWarningExcludingBoilerplate()
    {
        IReadOnlyList<string> warnings = DacFxUtils.ExtractWarnings(TestSample);

        string warning = Assert.Single(warnings);
        Assert.Contains("[dbo].[Member].[TestC]", warning);
        Assert.Contains("no default value and does not allow NULL", warning);
        // collapsed to a single line
        Assert.DoesNotContain("\n", warning);
        // boilerplate header / probe comments are not surfaced
        Assert.DoesNotContain(warnings, w => w.Contains("generated by a tool"));
    }

    [Fact]
    public void ExtractWarnings_NoWarnings_ReturnsEmpty()
    {
        const string clean = """
            ALTER TABLE [dbo].[Campus] ADD [TestA] BIT NULL;
            GO
            """;

        Assert.Empty(DacFxUtils.ExtractWarnings(clean));
    }

    [Fact]
    public void SplitByTable_ProducesOneScriptPerBatchTaggedWithItsTable()
    {
        string normalised = DacFxUtils.DenoiseScript(TestSample);

        IReadOnlyList<SchemaObjectScript> scripts = DacFxUtils.SplitScriptsByObject(normalised);

        Assert.Equal(3, scripts.Count);
        Assert.Single(scripts, s => s.Object.Name == "Campus");
        Assert.Equal(2, scripts.Count(s => s.Object.Name == "Member"));
    }

    [Fact]
    public void SplitByTable_KeepsDacFxEmissionOrder()
    {
        string normalised = DacFxUtils.DenoiseScript(TestSample);

        IReadOnlyList<SchemaObjectScript> scripts = DacFxUtils.SplitScriptsByObject(normalised);

        Assert.Contains("RAISERROR", scripts[0].Script);
        Assert.Contains("ALTER TABLE [dbo].[Campus]", scripts[1].Script);
        Assert.Contains("ALTER TABLE [dbo].[Member]", scripts[2].Script);
    }

    [Fact]
    public void SplitByTable_CampusScriptHoldsOnlyCampusDdl()
    {
        string normalised = DacFxUtils.DenoiseScript(TestSample);
        IReadOnlyList<SchemaObjectScript> scripts = DacFxUtils.SplitScriptsByObject(normalised);

        SchemaObjectScript campus = scripts.Single(s => s.Object.Name == "Campus");

        Assert.Contains("ALTER TABLE [dbo].[Campus]", campus.Script);
        Assert.DoesNotContain("[dbo].[Member]", campus.Script);
    }

    [Fact]
    public void SplitByTable_ScriptsContainNoBatchSeparators()
    {
        string normalised = DacFxUtils.DenoiseScript(TestSample);
        IReadOnlyList<SchemaObjectScript> scripts = DacFxUtils.SplitScriptsByObject(normalised);

        // each file is applied as one command — MigrationValidator rejects GO batch tokens
        Assert.All(scripts, s => Assert.False(ScriptDomUtils.ContainsBatchToken(s.Script)));
    }

    [Fact]
    public void SplitByTable_MemberGuardAndAlterAreSeparateScripts()
    {
        string normalised = DacFxUtils.DenoiseScript(TestSample);
        IReadOnlyList<SchemaObjectScript> scripts = DacFxUtils.SplitScriptsByObject(normalised);

        SchemaObjectScript[] member = [.. scripts.Where(s => s.Object.Name == "Member")];

        Assert.Contains("RAISERROR", member[0].Script);
        Assert.DoesNotContain("ALTER TABLE", member[0].Script);

        Assert.Contains("ALTER TABLE [dbo].[Member]", member[1].Script);
        Assert.DoesNotContain("RAISERROR", member[1].Script);
    }

    [Fact]
    public void SplitByTable_WarningFloatsToTheObjectsFirstScriptOnly()
    {
        string normalised = DacFxUtils.DenoiseScript(TestSample);
        IReadOnlyList<SchemaObjectScript> scripts = DacFxUtils.SplitScriptsByObject(normalised);

        SchemaObjectScript[] member = [.. scripts.Where(s => s.Object.Name == "Member")];

        // the warning is present exactly once across the object's scripts, and never on Campus
        Assert.Contains("no default value and does not allow NULL", member[0].Script);
        Assert.DoesNotContain("no default value", member[1].Script);
        Assert.Empty(member[1].Warnings);

        SchemaObjectScript campus = scripts.Single(s => s.Object.Name == "Campus");
        Assert.DoesNotContain("no default value", campus.Script);
    }

    [Fact]
    public void SplitByObject_ColumnAndTheIndexOverIt_StaySeparateScripts()
    {
        const string sql = """
            ALTER TABLE [dbo].[MemberRole]
                ADD [IsDefault] BIT CONSTRAINT [DF_MemberRole_IsDefault] DEFAULT ((0)) NOT NULL;
            GO
            CREATE UNIQUE NONCLUSTERED INDEX [IX_MemberRole_IsDefault]
                ON [dbo].[MemberRole]([IsDefault] ASC) WHERE [IsDefault] = 1;
            GO
            """;

        IReadOnlyList<SchemaObjectScript> scripts = DacFxUtils.SplitScriptsByObject(sql);

        Assert.Equal(2, scripts.Count);
        Assert.All(scripts, s => Assert.Equal("MemberRole", s.Object.Name));

        Assert.Contains("ALTER TABLE", scripts[0].Script);
        Assert.DoesNotContain("CREATE UNIQUE NONCLUSTERED INDEX", scripts[0].Script);

        Assert.Contains("CREATE UNIQUE NONCLUSTERED INDEX", scripts[1].Script);
        Assert.DoesNotContain("ALTER TABLE", scripts[1].Script);
    }

    [Fact]
    public void SplitByObject_WarningWithNoDdlOfItsOwn_StillEmitsAWarningOnlyScript()
    {
        const string sql = """
            /*
            The object [dbo].[Ghost] is referenced elsewhere and will not be dropped.
            */
            GO
            ALTER TABLE [dbo].[Campus] ADD [TestA] BIT NULL;
            GO
            """;

        IReadOnlyList<SchemaObjectScript> scripts = DacFxUtils.SplitScriptsByObject(sql);

        Assert.Equal(2, scripts.Count);

        SchemaObjectScript ghost = scripts.Single(s => s.Object.Name == "Ghost");

        Assert.Contains("referenced elsewhere", ghost.Script);
        Assert.DoesNotContain("ALTER TABLE", ghost.Script);
        Assert.Single(ghost.Warnings);
    }

    [Fact]
    public void SplitByObject_StoredProcedure_ClassifiedAsProcNotReferencedTable()
    {
        const string proc = """
            ALTER PROCEDURE [dbo].[usp_GetRosters]
            AS
            BEGIN
                /* GET THE ROSTERS */
                SELECT * FROM [dbo].[Roster];
            END
            GO
            """;

        IReadOnlyList<SchemaObjectScript> scripts = DacFxUtils.SplitScriptsByObject(proc);

        SchemaObjectScript script = Assert.Single(scripts);
        Assert.Equal("usp_GetRosters", script.Object.Name);
        Assert.Equal(SchemaObjectKind.StoredProcedure, script.Object.Kind);
        Assert.Contains("GET THE ROSTERS", script.Script);
        Assert.Empty(script.Warnings);
    }

    [Fact]
    public void SplitByObject_TableAndProcedure_EmitsBothWithoutCollapsing()
    {
        const string mixed = """
            ALTER TABLE [dbo].[Roster]
                ADD [Active] BIT NULL;
            GO
            ALTER PROCEDURE [dbo].[usp_GetRosters]
            AS
                SELECT * FROM [dbo].[Roster];
            GO
            """;

        IReadOnlyList<SchemaObjectScript> scripts = DacFxUtils.SplitScriptsByObject(mixed);

        Assert.Equal(2, scripts.Count);
        Assert.Contains(scripts, s => s.Object is { Name: "Roster", Kind: SchemaObjectKind.Table });
        Assert.Contains(scripts, s => s.Object is { Name: "usp_GetRosters", Kind: SchemaObjectKind.StoredProcedure });
    }
    [Fact]
    public void SplitScriptByBatch_SplitsOnGo()
    {
        string sql = "SELECT 1;\nGO\nSELECT 2;\nGO\nSELECT 3;";

        IReadOnlyList<string> batches = DacFxUtils.SplitScriptByBatch(sql);

        Assert.Equal(3, batches.Count);
        Assert.Contains(batches, b => b.Contains("SELECT 1;"));
        Assert.Contains(batches, b => b.Contains("SELECT 3;"));
    }

    [Fact]
    public void SplitScriptByBatch_KeepsSqlAndDropsBlanks()
    {
        string sql = "GO\n\nSELECT 1;\nGO\nGO\n   \nSELECT 2;\nGO\n";

        IReadOnlyList<string> batches = DacFxUtils.SplitScriptByBatch(sql);

        Assert.Equal(2, batches.Count);
        Assert.All(batches, b => Assert.False(string.IsNullOrWhiteSpace(b)));
    }

    [Fact]
    public void SplitScriptByBatch_NoSeparator_ReturnsSingleBatch()
    {
        IReadOnlyList<string> batches = DacFxUtils.SplitScriptByBatch("SELECT 1;");

        Assert.Single(batches);
    }

    [Fact]
    public void SplitScriptByBatch_OnlySeparators_ReturnsEmpty()
    {
        Assert.Empty(DacFxUtils.SplitScriptByBatch("  \nGO\n go \nGO\n  "));
    }

    [Fact]
    public void SplitScriptByBatch_TrimsEachBatch()
    {
        // the separator lines leave their surrounding whitespace on the batches either side
        IReadOnlyList<string> batches = DacFxUtils.SplitScriptByBatch("\n\n  SELECT 1;  \n\nGO\n\n\tSELECT 2;\t\n\n");

        Assert.Equal(["SELECT 1;", "SELECT 2;"], batches);
    }

}
