using MigDb.Core.Migration.Manifest;
using MigDb.Core.Utils.ScriptDom;
using Microsoft.Extensions.Logging;
using Microsoft.SqlServer.TransactSql.ScriptDom;
using System.Text.Json;

namespace MigDb.Core.Migration.Validation;

/// <summary>
/// Validates migration directories, their files and their manifests.
///
/// </summary>
/// <param name="hasher">Hasher used to re-hash directories being checked</param>
/// <param name="manifestStore">Store used to read the manifest being checked against</param>
/// <param name="logger">Logger to use</param>
public sealed class MigrationValidator(MigrationHasher hasher, MigrationManifestStore manifestStore, ILogger<MigrationValidator> logger)
{
    public const int MaxFiles = 99;

    /// <summary>
    /// Check a directory's current content against the hash recorded when it was applied.
    ///
    /// This is the only check that compares against the journal rather than against the
    /// manifest on disk. The manifest is regenerated by prepare, so it cannot detect an
    /// applied migration that was edited and then re-prepared - the recorded hash can.
    /// </summary>
    /// <param name="directory">The migration directory to re-hash</param>
    /// <param name="appliedHash">The directory hash recorded when the migration was applied</param>
    /// <returns>True when the directory no longer matches what was applied</returns>
    public async Task<bool> HasDriftedAsync(MigrationDirectory directory, byte[] appliedHash, CancellationToken ct = default)
    {
        MigrationDirectoryHashResult result = await hasher.HashDirectoryAsync(directory, ct);

        bool drifted = !result.DirectoryHash.SequenceEqual(appliedHash);

        if (drifted)
            logger.LogWarning("Directory {Directory} no longer matches the hash recorded when it was applied", directory.Name);

        return drifted;
    }

    /// <summary>
    /// Check file for plan and preparing errors
    /// </summary>
    /// <param name="file">The file to check</param>
    /// <returns>The validation errors found, empty when the file is valid</returns>
    public async Task<MigrationValidationResult> ValidateFileAsync(FileInfo file, CancellationToken ct = default)
    {
        List<MigrationValidationError> issues = [];

        logger.LogInformation("Validating file: {File}", file.Name);

        if (!file.Extension.Equals(".sql", StringComparison.OrdinalIgnoreCase))
        {
            logger.LogDebug("Non SQL file: {File}", file.Name);
            issues.Add(MigrationValidationError.NonSqlFiles);
        }

        string content = await File.ReadAllTextAsync(file.FullName, ct);

        MigrationValidationResult scriptErrors = ValidateSchemaScript(content);
        issues.AddRange(scriptErrors.Errors);

        if (issues.Contains(MigrationValidationError.ContainsBatchToken))
            logger.LogDebug("Detected batch token in: {File}", file.Name);

        if (issues.Contains(MigrationValidationError.SQLParseError))
            logger.LogDebug("Detected bad SQL in file: {File}", file.Name);

        if (issues.Count != 0)
            logger.LogDebug("File {File} has {Count} validation issue(s)", file.Name, issues.Count);

        return new(issues, file.Name);
    }

    public MigrationValidationResult ValidateBatches(FileInfo file, IReadOnlyList<string> batches)
    {
        List<MigrationValidationError> issues = [];

        logger.LogInformation("Validating {Count} batch(es) from: {File}", batches.Count, file.Name);

        if (!file.Extension.Equals(".sql", StringComparison.OrdinalIgnoreCase))
        {
            logger.LogDebug("Non SQL file: {File}", file.Name);
            issues.Add(MigrationValidationError.NonSqlFiles);
        }

        if (batches.Count == 0)
        {
            logger.LogDebug("No batches in: {File}", file.Name);
            issues.Add(MigrationValidationError.EmptyFile);
        }

        foreach (string batch in batches)
            issues.AddRange(ValidateSchemaScript(batch).Errors);

        if (issues.Count != 0)
            logger.LogDebug("File {File} has {Count} validation issue(s) across its batches", file.Name, issues.Count);

        return new(issues, file.Name);
    }

    public MigrationValidationResult ValidateSchemaScript(string sql) => ValidateScript(sql, [TSqlTokenType.Go]);

    public MigrationValidationResult ValidateProgrammableScript(string sql) => ValidateScript(sql, []);

    public MigrationValidationResult ValidateScript(string sql, IReadOnlyList<TSqlTokenType> disallowedTokens)
    {
        List<MigrationValidationError> issues = [];

        if (string.IsNullOrWhiteSpace(sql))
            issues.Add(MigrationValidationError.EmptyFile);

        foreach (TSqlTokenType token in ScriptDomUtils.FindTokens(sql, disallowedTokens))
        {
            var error = token switch
            {
                TSqlTokenType.Go => MigrationValidationError.ContainsBatchToken,
                _ => throw new ArgumentOutOfRangeException(nameof(token), token, "No validation error is mapped for this token"),
            };

            issues.Add(error);
        }

        // parse and validate SQL just in case
        IReadOnlyList<ParseError> parseErrors = ScriptDomUtils.Parse(sql);

        if (parseErrors.Count != 0)
        {
            issues.Add(MigrationValidationError.SQLParseError);

            foreach (ParseError e in parseErrors)
                logger.LogError("SQL parse error at line {Line}: {Message}", e.Line, e.Message);
        }

        return new(issues);
    }

    /// <summary>
    /// Verify the directory against its manifest
    /// Checks manifest exists, directory hash, file hashes and hash mismatch.
    /// Also checks files missing from manifest and files not in manifest from directory
    /// </summary>
    /// <param name="directory">The migration directory to verify</param>
    /// <returns>The validation errors found, empty when the manifest matches</returns>
    public async Task<IReadOnlyList<MigrationValidationError>> ValidateManifestAsync(MigrationDirectory directory, CancellationToken ct = default)
    {
        HashSet<MigrationValidationError> issues = [];

        logger.LogDebug("Validating manifest from: {Directory}", directory.Name);

        // TODO: Review
        // trying to avoid TOCTOU and hitting IO multiple times is proving difficult
        // ive introduced MigrationDirectoryHashResult as a way to
        // read and generate the hashes only once.
        try
        {
            MigrationManifest? manifest = await manifestStore.LoadManifestAsync(directory);

            if (manifest is null)
            {
                logger.LogDebug("Manifest missing for {Directory}", directory.Name);
                issues.Add(MigrationValidationError.ManifestMissing);
            }
            else
            {
                MigrationDirectoryHashResult directoryHash = await hasher.HashDirectoryAsync(directory, ct);

                if (!Convert.ToHexString(directoryHash.DirectoryHash).Equals(manifest.Hash, StringComparison.OrdinalIgnoreCase))
                {
                    logger.LogDebug("Hash mismatch for {Directory}", directory.Name);
                    issues.Add(MigrationValidationError.DirectoryHashMismatch);
                }

                foreach (MigrationManifestFile mF in manifest.Files)
                {
                    if (!directoryHash.Files.TryGetValue(mF.Name, out MigrationFileHashResult? lFResult))
                    {
                        logger.LogDebug("'{FileName}' in manifest is missing from: '{DirectoryName}'", mF.Name, directory.Name);
                        issues.Add(MigrationValidationError.FileInManifestMissing);
                        continue;
                    }

                    if (Convert.ToHexString(lFResult.Hash) != mF.Hash)
                    {
                        logger.LogDebug("'{FileName}' hash mismatch in '{Directory}'", mF.Name, directory.Name);
                        issues.Add(MigrationValidationError.FileHashMismatch);
                    }
                }

                HashSet<string> manifestFileNames = manifest.Files
                    .Select(x => x.Name)
                    .ToHashSet(StringComparer.Ordinal);

                List<string> untracked = directoryHash.Files.Keys
                    .Where(x => !manifestFileNames.Contains(x))
                    .ToList();

                foreach (string? fName in untracked)
                {
                    logger.LogDebug("File '{FileName}' missing from manifest in '{Directory}'", fName, directory.Name);
                    issues.Add(MigrationValidationError.FileNotInManifest);
                }
            }
        }
        catch (Exception e) when (e is JsonException or InvalidOperationException)
        {
            logger.LogDebug(e, "Invalid manifest in {Directory}", directory.Name);
            issues.Add(MigrationValidationError.CorruptedManifest);
        }

        return [.. issues];
    }

    /// <summary>
    /// Validate a directory for planning and preparing errors
    /// </summary>
    /// <param name="directory">The migration directory to check</param>
    /// <returns>The validation errors found, empty when the directory is valid</returns>   
    /// </summary>
    /// <param name="generatedNames">The names the plan will produce, in plan order</param>
    /// <returns>The validation errors found, empty when the plan is sound</returns>
    public IReadOnlyList<MigrationValidationError> ValidatePlannedNames(IReadOnlyList<string> generatedNames)
    {
        List<MigrationValidationError> issues = [];

        logger.LogDebug("Validating {Count} planned name(s)", generatedNames.Count);

        if (generatedNames.Count > MaxFiles)
        {
            logger.LogDebug("Planning would leave {Count} files, past the {Max} allowed", generatedNames.Count, MaxFiles);
            issues.Add(MigrationValidationError.TooManyFiles);
        }

        HashSet<string> seen = new(StringComparer.OrdinalIgnoreCase);

        foreach (string name in generatedNames)
        {
            if (seen.Add(name))
                continue;

            logger.LogDebug("More than one file plans to become {Name}", name);
            issues.Add(MigrationValidationError.GeneratedNameCollision);
        }

        return issues;
    }

    public IReadOnlyList<MigrationValidationError> ValidateDirectory(MigrationDirectory directory)
    {
        List<MigrationValidationError> issues = [];

        logger.LogInformation("Validating directory: {Directory}", directory.Name);

        if (directory.Info.GetDirectories().Length != 0)
        {
            logger.LogDebug("Sub directories found in {Directory}", directory.Name);
            issues.Add(MigrationValidationError.HasSubDirectories);
        }

        IReadOnlyList<FileInfo> dataFiles = directory.GetDataFiles();

        if (dataFiles.Count == 0)
        {
            logger.LogDebug("No files found in {Directory}", directory.Name);
            issues.Add(MigrationValidationError.Empty);
        }

        if (dataFiles.Count > MaxFiles)
        {
            logger.LogDebug("Too many files in {Directory}", directory.Name);
            issues.Add(MigrationValidationError.TooManyFiles);
        }

        if (issues.Count != 0)
            logger.LogDebug("Directory {Directory} has {Count} validation issue(s)", directory.Name, issues.Count);

        return issues;
    }

    /// <summary>
    /// Run full validation against a migration directory
    /// </summary>
    /// <param name="directory">The migration directory to validate</param>
    /// <returns>The combined validation result</returns>
    public async Task<MigrationValidationResult> ValidateDirectoryAsync(MigrationDirectory directory, CancellationToken ct = default)
    {
        HashSet<MigrationValidationError> issues = [];
        List<MigrationValidationResult> fileValidations = [];

        IReadOnlyList<MigrationValidationError> dIssues = ValidateDirectory(directory);
        issues.UnionWith(dIssues);

        foreach (FileInfo f in directory.GetDataFiles())
        {
            MigrationValidationResult vfr = await ValidateFileAsync(f, ct);

            // failures only, a clean file has nothing to say and would render as an empty node
            if (!vfr.IsValid)
                fileValidations.Add(vfr);
        }

        IReadOnlyList<MigrationValidationError> mIssues = await ValidateManifestAsync(directory, ct);
        issues.UnionWith(mIssues);

        if (issues.Count != 0)
            logger.LogDebug("Directory {Directory} has {Count} validation issue(s)", directory.Name, issues.Count);

        return new MigrationValidationResult([.. issues], directory.Name) { Children = fileValidations };
    }
}
